config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions'
  }
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    sessions: 'teachers/sessions'
  }
  devise_for :employees, controllers: {
    registrations: 'employees/registrations',
    sessions: 'employees/sessions'
  }
  resources :reports, only: [:create] do
    member do 
      get 'view'
      get 'new'
    end
    collection do
      get 'add_accounts'
      get 'back'
      get 'search'
      get 'choose_student'
    end
  end
  resources :study_materials, only: [:index, :new, :create]
  resources :material_relations, only: [:new, :create]
  root to: 'reports#choose_student'
end

app/models/study_material.rb
class StudyMaterial < ApplicationRecord
  has_many :material_relations
end

app/controllers/study_materials_controller.rb
class StudyMaterialsController < ApplicationController
  def index
  end

  def new
    @study_material = StudyMaterial.new
  end

  def create
    @study_material = StudyMaterial.new(study_material_params)
    if @study_material.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  private

  def study_material_params
    params.require(:study_material).permit(:name)
  end
end

app/helpers/study_materials_helper.rb
module StudyMaterialsHelper
end

app/views/study_materials/index.html.erb
<%= render "shared/header" %>
<div>
  <%= link_to '教材登録', new_study_material_path %>
</div>
<div>
  <%= link_to '生徒ごとの教材登録', new_material_relation_path %>
</div>

app/views/study_materials/new.html.erb
<%= render "shared/header" %>
<%= form_with model: @study_material, local: true do |f| %>
  <div>
  教材名
  <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit '記入完了' %>
  </div>
<% end %>