config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions'
  }
  devise_for :teachers, controllers: {
    registrations: 'teachers/registrations',
    sessions: 'teachers/sessions'
  }
  devise_for :employees, controllers: {
    registrations: 'employees/registrations',
    sessions: 'employees/sessions'
  }
  resources :reports, only: [:create] do
    member do 
      get 'view'
      get 'new'
    end
    collection do
      get 'add_accounts'
      get 'back'
      get 'search'
      get 'choose_student'
    end
  end
  resources :study_materials, only: [:index, :new, :create]
  resources :material_relations, only: [:new, :create]
  root to: 'reports#choose_student'
end

app/models/report.rb
class Report < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :lesson_type
  belongs_to :attendance_status

  def self.search(search)
    if search != ''
      Report.where('month LIKE(?)', "%#{search}%")
    else
      Report.last(8)
    end
  end

  def self.chose_student
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :move_to_index

  def view
    @student = Student.find(params[:id])
    @reports = Report.where(student_id: params[:id])
  end

  def new
    @report = Report.new
    @material_name = MaterialRelation.where(student_id: params[:id]).pluck(:material_name)
    @material_name << 'その他'
    @teacher = current_teacher.last_name
    gon.teacher = @teacher
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      student_id = params.require(:report).permit(:student_id).to_s.delete('^0-9')
      student = Student.find(student_id)
      redirect_to view_report_path(student.id)
    else
      render :new
    end
  end

  def search
    @reports = Report.search(params[:keyword])
  end

  def choose_student
    @students = Student.all
    redirect_to root_path if params[:student_name]
  end

  def add_accounts
    redirect_to new_student_session_path unless employee_signed_in?
  end

  def back
    redirect_to new_student_session_path unless employee_signed_in?
  end

  private

  def report_params
    params.require(:report).permit(:month, :date, :day, :subject, :time, :lesson_type_id, :attendance_status_id, :contact, :homework_status, :quiz, :quiz_result, :quiz_correspondence, :study_material, :other_study_material, :lesson_contents, :lesson_status, :retry_time, :homework, :teacher, :student_id)
  end

  def move_to_index
    redirect_to new_student_session_path unless employee_signed_in? || student_signed_in? || teacher_signed_in?
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_report.html.erb
<div class='report-flame'>
  <div>
    <%= report.month %>/<%= report.date %> (<%= report.day %>)
  </div>
  <div>
    科目：<%= report.subject %> <%= report.attendance_status.name %>
  </div>
    
  <div>
    授業時刻：<%= report.time %>
  </div>

  <div>
    授業種別：<%= report.lesson_type.name %>
  </div>

  <div>
    連絡事項：<%= report.contact %>
  </div>

  <div>
    宿題チェック：<%= report.homework_status %>
  </div>

  <div>
    確認テスト：<%= report.quiz %>
  </div>

  <div>
    結果：<%= report.quiz_result %>
  </div>

  <div>
    教材：
    <% if report.study_material == 'その他' %>
      <%= report.other_study_material %>
    <% else %>
      <%= report.study_material %>
    <% end %>
  </div>

  <div>
    授業内容：<%= report.lesson_contents %>
  </div>

  <div>
    リトライタイム：<%= report.retry_time %>
  </div>

  <div>
    宿題：<%= report.homework %>
  </div>

  <div>
    担当講師：<%= report.teacher %>
  </div>
</div>

app/views/reports/add_accounts.erb
<%= render "shared/header" %>

<div>
<%= link_to '生徒登録', new_student_registration_path %>
</div>
<div>
<%= link_to '講師登録', new_teacher_registration_path %>
</div>

app/views/reports/add_accounts.html.erb
<%= render "shared/header" %>

<div>
<%= link_to '生徒登録', new_student_registration_path %>
</div>
<div>
<%= link_to '講師登録', new_teacher_registration_path %>
</div>

app/views/reports/back.html.erb
登録が完了しました。

<div>
  <% if teacher_signed_in? %>
    <%= link_to "homeに戻る", destroy_teacher_session_path, method: :delete %>
  <% elsif student_signed_in? %>
    <%= link_to "homeに戻る", destroy_student_session_path, method: :delete %>
  <% end %>
</div>

app/views/reports/choose_student.html.erb
<h2>
  生徒選択
</h2>

<% @students.each do |student| %>
  <div>
  <%= link_to student.first_name ,view_report_path(student.id) %>
  </div>
<% end %>

app/views/reports/new.html.erb
<%= render "shared/header" %>

<div class="reports-new-main">
  <%= form_with model: @report, local: true do |f| %>
    <div>
      日付
      <%= f.text_field :month %><%= f.text_field :date %>
    </div>
    <div>
      曜日
      <%= f.text_field :day %>
    </div>
    <div>
      科目
      <%= f.select :subject, [["--",""],["国語","国語"],["数学","数学"],["理科","理科"],["社会","社会"],["英語","英語"]]%>
    </div>
    <div>
      授業時刻
      <%= f.text_field :time %>
    </div>
    
    <div>
      授業形式
      <%= f.collection_select(:lesson_type_id, LessonType.all, :id, :name, {}) %>
    </div>

    <div>
      出欠
      <%= f.collection_select(:attendance_status_id, AttendanceStatus.all, :id, :name, {}) %>
    </div>

    <div>
      連絡事項
      <%= f.text_field :contact %>
    </div>

    <div>
      宿題チェック
      <%= f.text_field :homework_status %>
    </div>

    <div>
      確認テスト
      <%= f.text_field :quiz %>
    </div>

    <div>
      結果
      <%= f.text_field :quiz_result %>
    </div>

    <div>
      教材
      <%= f.select :study_material, @material_name, prompt: "--" %>
    </div>
    <div>
      <%= f.text_field :other_study_material, class: 'other_study_material',placeholder: 'その他の教材名を入力' %>
    </div>

    <div>
      授業内容
      <%= f.text_area :lesson_contents %>
    </div>
    <div>
      リトライタイム
      <%= f.text_field :retry_time %>
    </div>
    <div>
      宿題
      <%= f.text_field :homework %>
    </div>
    <div>
      担当講師
      <%= f.text_field :teacher %>
    </div>

    <div>
      <%= f.hidden_field :student_id, value: params[:id] %>
    </div>

    <div>
      <%= f.submit '記入完了' %>
    </div>
  <% end %>
</div>

app/views/reports/search.html.erb
<%= render "shared/header" %>

<div>
  <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "過去のカルテを検索する", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>
</div>
<div>
  <%= render partial: "report", collection: @reports %>
</div>

app/views/reports/view.html.erb
<%= render "shared/header" %>

<div>
  <% if teacher_signed_in? %>
  <div>
  <%= @student.last_name %> <%= @student.first_name %> さんのカルテ
  </div>
  <div>
    <%= link_to '教材登録ページへ', study_materials_path %>
  </div>
  <div>
    <%= link_to '新規カルテ作成', report_path(params[:id]), params.merge(student_id: params[:id]) %>
  </div>
  <% end %>
</div>

<div>
  <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "過去のカルテを検索する", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>
</div>
<div>
  <%= render partial: "report", collection: @reports %>
</div>